# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dividend_yield',
            name='year',
        ),
        migrations.AlterField(
            model_name='dividend_yield',
            name='period',
            field=models.DateField(),
        ),
    ]
