# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0002_auto_20170111_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividend_payout',
            name='year',
            field=models.IntegerField(default=2010),
        ),
        migrations.AddField(
            model_name='dividend_yield',
            name='year',
            field=models.IntegerField(default=2010),
        ),
        migrations.AddField(
            model_name='financial_ratio',
            name='year',
            field=models.IntegerField(default=2010),
        ),
        migrations.AddField(
            model_name='financial_statement',
            name='year',
            field=models.IntegerField(default=2010),
        ),
        migrations.AlterField(
            model_name='dividend_payout',
            name='quarter',
            field=models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')]),
        ),
        migrations.AlterField(
            model_name='dividend_yield',
            name='quarter',
            field=models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')]),
        ),
        migrations.AlterField(
            model_name='financial_ratio',
            name='quarter',
            field=models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')]),
        ),
        migrations.AlterField(
            model_name='financial_statement',
            name='quarter',
            field=models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')]),
        ),
    ]
