# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0002_auto_20170330_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='fair_value',
            name='payout_status',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fair_value',
            name='rental_status',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fair_value',
            name='retained_status',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fair_value',
            name='yield_status',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
