# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0002_auto_20170208_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dividend_payout',
            name='year',
        ),
        migrations.RemoveField(
            model_name='fair_value',
            name='year',
        ),
        migrations.RemoveField(
            model_name='financial_ratio',
            name='year',
        ),
        migrations.RemoveField(
            model_name='financial_statement',
            name='year',
        ),
        migrations.AlterField(
            model_name='dividend_payout',
            name='period',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fair_value',
            name='period',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='financial_ratio',
            name='period',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='financial_statement',
            name='period',
            field=models.DateField(),
        ),
    ]
