# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0003_auto_20170208_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='general_information',
            name='latest_yield',
        ),
    ]
