# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-03 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0003_auto_20170330_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='fair_value',
            name='ddm_fair',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8, null=True),
        ),
    ]
