# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0003_auto_20170116_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividend_payout',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'Quarter 1'), ('Q2', 'Quarter 2'), ('Q3', 'Quarter 3'), ('Q4', 'Quarter 4')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dividend_yield',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'Quarter 1'), ('Q2', 'Quarter 2'), ('Q3', 'Quarter 3'), ('Q4', 'Quarter 4')], max_length=10),
        ),
        migrations.AlterField(
            model_name='financial_ratio',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'Quarter 1'), ('Q2', 'Quarter 2'), ('Q3', 'Quarter 3'), ('Q4', 'Quarter 4')], max_length=10),
        ),
        migrations.AlterField(
            model_name='financial_statement',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'Quarter 1'), ('Q2', 'Quarter 2'), ('Q3', 'Quarter 3'), ('Q4', 'Quarter 4')], max_length=10),
        ),
    ]
