# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0004_auto_20170116_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dividend_payout',
            name='quarter',
        ),
        migrations.RemoveField(
            model_name='dividend_yield',
            name='quarter',
        ),
        migrations.RemoveField(
            model_name='financial_ratio',
            name='quarter',
        ),
        migrations.RemoveField(
            model_name='financial_statement',
            name='quarter',
        ),
        migrations.AddField(
            model_name='dividend_payout',
            name='period',
            field=models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], default='Jan', max_length=5),
        ),
        migrations.AddField(
            model_name='dividend_yield',
            name='period',
            field=models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], default='Jan', max_length=5),
        ),
        migrations.AddField(
            model_name='financial_ratio',
            name='period',
            field=models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], default='Jan', max_length=5),
        ),
        migrations.AddField(
            model_name='financial_statement',
            name='period',
            field=models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], default='Jan', max_length=5),
        ),
    ]
