# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0004_remove_general_information_latest_yield'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial_ratio',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='financial_statement',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='general_information',
            name='fund_type',
            field=models.CharField(choices=[('Leasehold & Freehold', 'Leasehold & Freehold'), ('Leasehold', 'Leasehold'), ('Freehold', 'Freehold')], default='Leasehold', max_length=20),
        ),
    ]
