# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0004_fair_value_ddm_fair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_information',
            name='listed_share',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
