# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0005_auto_20170118_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratio_Cal',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('valuation.financial_ratio',),
        ),
        migrations.RemoveField(
            model_name='financial_ratio',
            name='roe',
        ),
        migrations.AddField(
            model_name='financial_ratio',
            name='eps',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='general_information',
            name='listed_share',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
