# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0005_auto_20170411_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('short_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valuation.General_Information')),
            ],
        ),
    ]
