# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0006_remove_financial_statement_quarter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financial_ratio',
            name='stability1',
        ),
        migrations.RemoveField(
            model_name='financial_ratio',
            name='stability2',
        ),
    ]
