# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0006_feednews'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial_ratio',
            name='bvps',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='financial_ratio',
            name='pbv',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
