# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0006_auto_20170123_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fair_Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], default='Jan', max_length=5)),
                ('year', models.IntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('fair', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('short_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valuation.General_Information')),
            ],
        ),
        migrations.DeleteModel(
            name='Ratio_Cal',
        ),
        migrations.AlterField(
            model_name='dividend_payout',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dividend_yield',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='financial_ratio',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='financial_statement',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
