# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0008_auto_20170126_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='fair_value',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fair_value',
            name='period',
            field=models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], default='Jan', max_length=5),
        ),
    ]
