# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0009_remove_financial_ratio_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='feednews',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
